name: Test Server Endpoints

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  unit-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: server

      - name: Run tests
        run: npm run test
        working-directory: server
